name: Deploy to Local Machine

# on:
#   workflow_run:
#     workflows: ["Docker Build and Push"]
#     types:
#       - completed
#     branches:
#       - docker-build
on:
  push:
    branches:
      - docker-build

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-client-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:ci

      - name: Deploy to server
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" > ~/.ssh/config

          # Deploy commands
          ssh $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            cd ~/Documents/vjt/hexray/practice/CI-CD  
            docker-compose pull
            docker-compose up -d
            docker image prune -f
          EOF
