name: Deploy to Local Machine

on:
  workflow_run:
    workflows: ["Docker Build and Push"]  # Make sure this exactly matches the name in docker-build.yml
    types:
      - completed
    branches:
      - "docker-build"   # Make sure this matches your branch name exactly

jobs:
  deploy:
    runs-on: ubuntu-22.04
    # Adding logging to debug the trigger condition
    steps:
      - name: Debug Information
        run: |
          echo "Triggered by workflow: ${{ github.event.workflow_run.name }}"
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"

      - name: Setup Tailscale
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-client-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:ci

      - name: Deploy to server
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" > ~/.ssh/config

          # Deploy commands
          ssh $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            cd ~/Documents/vjt/hexray/practice/CI-CD  
            docker-compose pull
            docker-compose up -d
            docker image prune -f
          EOF