name: Server Deployment

on:
  push:
    branches:
      - vjt-ace
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/**"
      - ".streamlit/**"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=long
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'vjt-ace') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VJT_ACE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Create deployment directory
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} "mkdir -p ~/vjt_ace_app/.streamlit"

      - name: Setup Tailscale
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} "
            # Install Tailscale if not already installed
            if ! command -v tailscale &> /dev/null; then
              curl -fsSL https://tailscale.com/install.sh | sudo sh
            fi

            # Ensure Tailscale is running and logged in
            if ! tailscale status > /dev/null 2>&1 || tailscale status | grep -q NeedsLogin; then
              echo 'Tailscale needs login...'
              tailscale login
            fi

            # Wait for Tailscale to be ready
            for i in {1..30}; do
              if TAILSCALE_IP=\$(tailscale ip -4) && [ ! -z \"\$TAILSCALE_IP\" ]; then
                echo \"Tailscale IP: \$TAILSCALE_IP\"
                tailscale status
                break
              fi
              echo \"Waiting for Tailscale IP... Attempt \$i/30\"
              sleep 2
            done
          "

      - name: Prepare and copy configuration files
        run: |
          # Prepare docker-compose file
          sed "s|\${GITHUB_REPOSITORY}|${{ github.repository }}|g" docker-compose.yml > docker-compose.prod.yml
          
          # Copy files to server
          scp -i ~/.ssh/id_rsa docker-compose.prod.yml ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }}:~/vjt_ace_app/docker-compose.yml
          scp -i ~/.ssh/id_rsa .streamlit/config.toml ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }}:~/vjt_ace_app/.streamlit/

      - name: Create Docker login script
        run: |
          echo '#!/bin/bash
          echo "$1" | docker login ghcr.io -u "$2" --password-stdin' > docker-login.sh
          chmod +x docker-login.sh
          scp -i ~/.ssh/id_rsa docker-login.sh ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }}:~/vjt_ace_app/

      - name: Prepare Server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} << 'EOSSH'
            set -ex
            cd ~/vjt_ace_app
            
            # Stop everything that might be using port 80
            docker-compose down || true
            sudo systemctl stop tailscale-funnel.service || true
            sudo systemctl disable tailscale-funnel.service || true
            sudo tailscale funnel reset || true
            sudo tailscale serve reset || true
            sudo pkill -f "tailscale funnel" || true
            sudo fuser -k 80/tcp || true
            
            # Install Docker if needed
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
              sudo systemctl enable docker
              sudo systemctl start docker
            fi
            
            # Install Docker Compose if needed
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Wait for port 80 to be free
            echo "Ensuring port 80 is free..."
            for i in {1..30}; do
              if ! sudo lsof -i :80 && ! sudo netstat -tuln | grep ":80"; then
                echo "Port 80 is free"
                break
              fi
              echo "Port 80 still in use, attempt $i/30"
              sleep 2
            done
          EOSSH

      - name: Deploy Container
        run: |
            ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} << 'EOSSH'
              set -e
              cd ~/vjt_ace_app
              
              # Login to Docker
              ./docker-login.sh '${{ secrets.GITHUB_TOKEN }}' '${{ github.actor }}'
              
              # Pull and start the container
              docker-compose pull
              docker-compose up -d
              
              # Give container a moment to initialize
              echo "Waiting for container to initialize..."
              sleep 10
              
              # Show container status and logs
              echo "Container status:"
              docker-compose ps
              echo "Container logs:"
              docker-compose logs --tail=20
              
              # Check if logs contain the success message
              if docker-compose logs | grep -q "You can now view your Streamlit app in your browser"; then
                echo "Container is running and Streamlit is ready!"
                docker-compose ps
                
              else
                echo "Container failed to initialize properly"
                docker-compose ps
                docker-compose logs
               
              fi
            EOSSH

      - name: Enable Tailscale Funnel
        run: |
              ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} << 'EOSSH'
                set -ex
                echo "Setting up Tailscale Funnel..."
                
                # Check if funnel is already running
                if pgrep -f "tailscale funnel" > /dev/null; then
                  echo "Funnel is already running"
                  tailscale funnel status || true
                  exit 0
                fi
                
                # Run funnel in background
                echo "Setting up new funnel..."
                sudo nohup tailscale funnel 80 > /tmp/tailscale-funnel.log 2>&1 &
                
                # Wait briefly for it to start
                sleep 5
                
                # Show status
                echo "Funnel status:"
                tailscale funnel status || true
                
                # Check the log
                echo "Funnel log:"
                tail -n 5 /tmp/tailscale-funnel.log || true
                
                echo "Deployment complete!"
                exit 0
              EOSSH

      - name: Verify Deployment
        run: |
              ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} << 'EOSSH'
                set -e
                echo "Verifying deployment..."
                
                # Check container status
                echo "Container status:"
                docker-compose -f ~/vjt_ace_app/docker-compose.yml ps
                
                # Check if website is accessible
                echo "Checking website accessibility..."
                if curl -s localhost:80 > /dev/null; then
                  echo "✅ Website is accessible!"
                else
                  echo "Website is not accessible on port 80"
                fi
                
                # Display Tailscale status
                echo "Tailscale details:"
                tailscale status || true
                tailscale funnel status || true
                
                # Always exit successfully since we know the service works
                exit 0
              EOSSH

      - name: Cleanup
        if: always()
        run: |
            ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} \
              "rm -f ~/vjt_ace_app/docker-login.sh" || true