name: Server Deployment

on:
  push:
    branches:
      - vjt-ace
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/**"
      - ".streamlit/**"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=long
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'vjt-ace') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VJT_ACE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Create deployment directory
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} "mkdir -p ~/vjt_ace_app/.streamlit"

      - name: Setup Tailscale
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} "
            # Install Tailscale if not already installed
            if ! command -v tailscale &> /dev/null; then
              curl -fsSL https://tailscale.com/install.sh | sudo sh
            fi

            # Ensure Tailscale is running and logged in
            if ! tailscale status > /dev/null 2>&1 || tailscale status | grep -q NeedsLogin; then
              echo 'Tailscale needs login...'
              tailscale login
            fi

            # Wait for Tailscale to be ready
            for i in {1..30}; do
              if TAILSCALE_IP=\$(tailscale ip -4) && [ ! -z \"\$TAILSCALE_IP\" ]; then
                echo \"Tailscale IP: \$TAILSCALE_IP\"
                tailscale status
                break
              fi
              echo \"Waiting for Tailscale IP... Attempt \$i/30\"
              sleep 2
            done
          "

      - name: Prepare and copy configuration files
        run: |
          # Prepare docker-compose file
          sed "s|\${GITHUB_REPOSITORY}|${{ github.repository }}|g" docker-compose.yml > docker-compose.prod.yml
          
          # Copy files to server
          scp -i ~/.ssh/id_rsa docker-compose.prod.yml ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }}:~/vjt_ace_app/docker-compose.yml
          scp -i ~/.ssh/id_rsa .streamlit/config.toml ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }}:~/vjt_ace_app/.streamlit/

      - name: Create Docker login script
        run: |
          echo '#!/bin/bash
          echo "$1" | docker login ghcr.io -u "$2" --password-stdin' > docker-login.sh
          chmod +x docker-login.sh
          scp -i ~/.ssh/id_rsa docker-login.sh ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }}:~/vjt_ace_app/

      - name: Prepare Server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} << 'EOSSH'
            set -ex
            cd ~/vjt_ace_app
            
            # Stop everything that might be using port 80
            docker-compose down || true
            sudo systemctl stop tailscale-funnel.service || true
            sudo systemctl disable tailscale-funnel.service || true
            sudo tailscale funnel reset || true
            sudo tailscale serve reset || true
            sudo pkill -f "tailscale funnel" || true
            sudo fuser -k 80/tcp || true
            
            # Install Docker if needed
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
              sudo systemctl enable docker
              sudo systemctl start docker
            fi
            
            # Install Docker Compose if needed
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Wait for port 80 to be free
            echo "Ensuring port 80 is free..."
            for i in {1..30}; do
              if ! sudo lsof -i :80 && ! sudo netstat -tuln | grep ":80"; then
                echo "Port 80 is free"
                break
              fi
              echo "Port 80 still in use, attempt $i/30"
              sleep 2
            done
          EOSSH

      - name: Deploy Container
        run: |
            ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} << 'EOSSH'
              set -e
              cd ~/vjt_ace_app
              
              # Login to Docker
              ./docker-login.sh '${{ secrets.GITHUB_TOKEN }}' '${{ github.actor }}'
              
              # Pull and start the container
              docker-compose pull
              docker-compose up -d
              
              # Wait for container to be healthy
              echo "Waiting for container to be healthy..."
              for i in {1..30}; do
                if docker-compose ps | grep -q "healthy"; then
                  echo "Container is healthy!"
                  docker-compose ps
                  docker-compose logs --tail=20
                  exit 0
                fi
                echo "Attempt $i: Waiting for container health check..."
                sleep 5
              done
              
              echo "Container failed to become healthy in time"
              docker-compose ps
              docker-compose logs
              exit 1
            EOSSH
  
      - name: Setup Tailscale Funnel
        if: success()  # Only run if previous steps succeeded
        run: |
            # Create funnel setup script
            cat << 'EOF' > setup_funnel.sh
            #!/bin/bash
            set -e
  
            echo "Setting up Tailscale Funnel..."
            
            # First, clean up any existing funnel/serve configurations
            echo "Cleaning up existing configurations..."
            sudo tailscale funnel reset || true
            sudo tailscale serve reset || true
            
            # Enable funnel
            echo "Enabling Tailscale funnel..."
            sudo tailscale funnel on || true
            
            # Set up funnel for port 80
            echo "Setting up funnel for port 80..."
            sudo tailscale funnel 80
  
            # Set up serve configuration
            echo "Setting up serve configuration..."
            sudo tailscale serve 80
  
            # Wait for funnel to be ready
            echo "Waiting for funnel to be ready..."
            for i in {1..30}; do
              if tailscale funnel status | grep -q "https://"; then
                echo "Funnel is ready!"
                tailscale funnel status
                exit 0
              fi
              echo "Attempt $i/30: Waiting for funnel..."
              sleep 2
            done
  
            echo "Error: Failed to set up funnel"
            tailscale funnel status
            exit 1
            EOF
  
            # Copy and execute script
            scp -i ~/.ssh/id_rsa setup_funnel.sh ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }}:~/
            ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} "chmod +x ~/setup_funnel.sh && ~/setup_funnel.sh"
            ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} "rm -f ~/setup_funnel.sh"
  
      - name: Verify Deployment
        if: success()  # Only run if previous steps succeeded
        run: |
            function verify_with_retry() {
              local cmd="$1"
              local desc="$2"
              local max_attempts=5
              
              for i in $(seq 1 $max_attempts); do
                echo "Attempting $desc (try $i/$max_attempts)..."
                if ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} "$cmd"; then
                  return 0
                fi
                sleep 5
              done
              return 1
            }
  
            echo "Verifying deployment..."
  
            # Verify container status
            if ! verify_with_retry "cd ~/vjt_ace_app && docker-compose ps" "container status check"; then
              echo "❌ Container verification failed"
              verify_with_retry "cd ~/vjt_ace_app && docker-compose logs" "getting container logs"
              exit 1
            fi
  
            # Verify funnel setup
            if ! verify_with_retry "tailscale funnel status" "funnel status check"; then
              echo "❌ Funnel verification failed"
              exit 1
            fi
  
            # Get funnel URL
            FUNNEL_URL=$(ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} "tailscale funnel status | grep 'https://' | awk '{print \$1}'")
            
            if [ ! -z "$FUNNEL_URL" ]; then
              echo "✅ Deployment successful!"
              echo "Your application is available at: $FUNNEL_URL"
            else
              echo "❌ Failed to get Funnel URL"
              verify_with_retry "tailscale status" "getting Tailscale status"
              exit 1
            fi
  
      - name: Cleanup
        if: always()
        run: |
            ssh -i ~/.ssh/id_rsa ${{ secrets.VJT_ACE_USER }}@${{ secrets.VJT_ACE_HOST }} "rm -f ~/vjt_ace_app/docker-login.sh" || true
      