name: Server Deployment

on:
  push:
    branches:
      - vjt-ace
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/**"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=long
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'production') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VJT_ACE_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Create deployment directory
        env:
          SERVER_HOST: ${{ secrets.VJT_ACE_HOST }}
          SERVER_USER: ${{ secrets.VJT_ACE_USER }}
        run: |
          ssh $VJT_ACE_USER@$VJT_ACE_HOST << 'EOF'
            # Create project directory if it doesn't exist
            mkdir -p ~/vjt_ace_app
          EOF

      - name: Copy Docker Compose file
        env:
          SERVER_HOST: ${{ secrets.VJT_ACE_HOST }}
          SERVER_USER: ${{ secrets.VJT_ACE_USER }}
        run: |
          scp docker-compose.yml $VJT_ACE_USER@$VJT_ACE_HOST:~/vjt_ace_app/

      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.VJT_ACE_HOST }}
          SERVER_USER: ${{ secrets.VJT_ACE_USER }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          ssh $VJT_ACE_USER@$VJT_ACE_HOST << 'EOF'
            set -ex
            cd ~/vjt_ace_app
            
            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              echo "Docker not found, installing..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
            fi
            
            # Install Docker Compose if not installed
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose not found, installing..."
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            # Login to GitHub Container Registry
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Deploy
            docker-compose pull
            docker-compose up -d
            
            # Cleanup
            docker image prune -f
            
            # Check deployment status
            docker ps
            docker-compose logs --tail=50
          EOF