[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
port = 8501
address = "0.0.0.0"
headless = true
baseUrlPath = "/"
maxUploadSize = 50
runOnSave = false

[browser]
serverAddress = "" 
serverPort = 8501
gatherUsageStats = false


