[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = false
port = 8501
address = "0.0.0.0"
headless = true

[browser]
serverAddress = "0.0.0.0" 
serverPort = 8501
gatherUsageStats = false